name = "eztravels"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "eztravels"

[env.staging]
name = "eztravels-staging"

[build]
command = "npm run pages:build" 